version: "3"
services:
  kepplr-node-service:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run start:dev

  mongo-container:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_root_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_root_pwd